//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Students = new HashSet<Student>();
            this.Quizzes = new HashSet<Quiz>();
            this.Assignments = new HashSet<Assignment>();
            this.Announcements = new HashSet<Announcement>();
            this.Discussions = new HashSet<Discussion>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int TeacherId { get; set; }
        public bool Active { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Quiz> Quizzes { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<Discussion> Discussions { get; set; }
    }
}
