//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestionSolution
    {
        public int Id { get; set; }
        public Nullable<int> SelectedOption { get; set; }
        public int QuizSolutionId { get; set; }
        public bool IsCorrect { get; set; }
        public int QuizQuestionId { get; set; }
    
        public virtual QuizSolution QuizSolution { get; set; }
        public virtual QuizQuestion Question { get; set; }
    }
}
