//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSolution
    {
        public QuizSolution()
        {
            this.QuestionSolutions = new HashSet<QuizQuestionSolution>();
        }
    
        public int Id { get; set; }
        public int QuizId { get; set; }
        public int StudentId { get; set; }
        public int Correct { get; set; }
        public int Marks { get; set; }
        public int Attempted { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<QuizQuestionSolution> QuestionSolutions { get; set; }
    }
}
