//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public QuizQuestion()
        {
            this.Solutions = new HashSet<QuizQuestionSolution>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public int CorrectOption { get; set; }
        public int Marks { get; set; }
        public int QuizId { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual ICollection<QuizQuestionSolution> Solutions { get; set; }
    }
}
