//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Courses = new HashSet<Course>();
            this.QuizSolutions = new HashSet<QuizSolution>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string Website { get; set; }
        public string PasswordResetPIN { get; set; }
        public bool EmailConfirmed { get; set; }
        public string EmailConfirmationPIN { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<QuizSolution> QuizSolutions { get; set; }
    }
}
